[tool.poetry]
name = "OKX_news_parser"
version = "1.0"
description = 'OKX news parser'

[tool.poetry.dependencies]
python = "^3.6"
beautifulsoup4 = "^4.12.2"
Requests = "^2.32.3"

[build-system]
requires = ["poetry>=0.12", "setuptools"]
